const INCREMENT = 'INCREMENT';
const TOGGLE_VIRTUALIZATION = 'TOGGLE_VIRTUALIZATION';
const UPDATE_FILTERS = 'UPDATE_FILTERS';
const UPDATE_SORT_DIRECTION = 'UPDATE_SORT_DIRECTION';

export {
  INCREMENT, TOGGLE_VIRTUALIZATION, UPDATE_FILTERS, UPDATE_SORT_DIRECTION,
};
