const TOGGLE_VIRTUALIZATION = 'TOGGLE_VIRTUALIZATION';
const TOGGLE_ROW_SELECTION = 'TOGGLE_ROW_SELECTION';
const UPDATE_FILTERS = 'UPDATE_FILTERS';
const APPLY_FIRST_PRIORITY = 'APPLY_FIRST_PRIORITY';
const APPLY_ADDITIONAL_PRIORITY = 'APPLY_ADDITIONAL_PRIORITY';

export {
  TOGGLE_VIRTUALIZATION,
  TOGGLE_ROW_SELECTION,
  UPDATE_FILTERS,
  APPLY_FIRST_PRIORITY,
  APPLY_ADDITIONAL_PRIORITY,
};
